name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: 
         chmod +x configure 
        ./configure
    - name: make
      run: make all
    - name: make check
      run: echo "might be checking for assets.."
    - name: make distcheck
      run: echo "might be checking the distribution"
